name = "LeanLoad"
version = "0.1.0"
defaultTargets = ["leanload"]
testDriver = "test"

[[lean_lib]]
name = "LeanLoad"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "leanload"
root = "Main"

[[lean_exe]]
name = "test"
root = "Tests.Test"
