/-
Parser monad and byte-reader primitives.

Three layers:

1. **Parser monad**: `StateT State (Except String)` — a stateful read
   cursor over a `ByteArray` that may fail with a string error.
   Every primitive bumps the cursor by exactly the bytes it consumes.

2. **`BytesDecode` typeclass**: type-driven dispatch. Each fixed-width
   integer (`UInt8/16/32/64`) plus the helper types `Pad n` (skip n
   bytes) and `Magic bs` (verify literal bytes) instantiate the
   class. The deriving handler (`Parse/Deriving.lean`) generates
   `BytesDecode` for any structure whose fields are all `BytesDecode`.

3. **`Bytes.decodeArray`**: read `count` `α`-entries via the typeclass.

Endianness is fixed to little-endian — gabi 02 § ELF Identification
allows either, but LeanLoad targets x86-64 and AArch64 ELFs (both
little-endian); the `ei_data` semantic check rejects big-endian
inputs at `Elaborate.elaborate`.
-/

namespace LeanLoad.Parse

/-- Parse state: source bytes plus current cursor offset. -/
structure State where
  bytes : ByteArray
  pos   : Nat

/-- Parser monad: stateful reads over a `ByteArray`, may fail with a message. -/
abbrev Parser (α : Type) : Type := StateT State (Except String) α

/-- Run a parser starting at offset 0. -/
def Parser.run (b : ByteArray) (p : Parser α) : Except String α :=
  Prod.fst <$> StateT.run p ({ bytes := b, pos := 0 } : State)

namespace Bytes

/-- Current cursor offset. -/
def pos : Parser Nat := return (← get).pos

/-- Move the cursor to an absolute offset. Does not read. -/
def seek (off : Nat) : Parser Unit :=
  modify ({ · with pos := off })

/-- Skip `n` bytes from the current position. -/
def skip (n : Nat) : Parser Unit :=
  modify (fun s => { s with pos := s.pos + n })

/-- Read one byte. Fails on EOF. -/
def u8 : Parser UInt8 := do
  let s ← get
  if s.pos < s.bytes.size then
    set { s with pos := s.pos + 1 }
    return s.bytes[s.pos]!
  else
    throw s!"u8: EOF at offset {s.pos}/{s.bytes.size}"

/-- Read a little-endian 16-bit unsigned. -/
def u16le : Parser UInt16 := do
  let lo ← u8
  let hi ← u8
  return lo.toUInt16 ||| (hi.toUInt16 <<< 8)

/-- Read a little-endian 32-bit unsigned. -/
def u32le : Parser UInt32 := do
  let lo ← u16le
  let hi ← u16le
  return lo.toUInt32 ||| (hi.toUInt32 <<< 16)

/-- Read a little-endian 64-bit unsigned. -/
def u64le : Parser UInt64 := do
  let lo ← u32le
  let hi ← u32le
  return lo.toUInt64 ||| (hi.toUInt64 <<< 32)

/-- Read `n` bytes as a sub-array. -/
def slice (n : Nat) : Parser ByteArray := do
  let s ← get
  if s.pos + n > s.bytes.size then
    throw s!"slice: out of bounds at {s.pos}+{n} (size {s.bytes.size})"
  set { s with pos := s.pos + n }
  return s.bytes.extract s.pos (s.pos + n)

/-- Read an exact byte sequence; fail if any byte mismatches. -/
def expect (expected : Array UInt8) : Parser Unit := do
  for byte in expected do
    let actual ← u8
    if actual != byte then
      throw s!"expect: got {actual}, want {byte}"

end Bytes

-- ============================================================================
-- BytesDecode typeclass — type-driven dispatch for the byte parsers.
-- ============================================================================

/-- A type whose value can be decoded from a byte stream by the
    parser monad. Each Parse struct gets a `BytesDecode` instance
    auto-generated by `deriving BytesDecode` (handler in
    `Parse/Deriving.lean`); primitives below cover fixed-width
    integers, padding, and magic-byte checks. -/
class BytesDecode (α : Type) where decode : Parser α

namespace BytesDecode

instance : BytesDecode UInt8  := ⟨Bytes.u8⟩
instance : BytesDecode UInt16 := ⟨Bytes.u16le⟩
instance : BytesDecode UInt32 := ⟨Bytes.u32le⟩
instance : BytesDecode UInt64 := ⟨Bytes.u64le⟩

end BytesDecode

/-- `n` bytes of don't-care padding. The decoder skips them; nothing
    is retained. Used as a struct field to consume layout padding
    (e.g. `e_ident`'s 7-byte `EI_PAD`). -/
structure Pad (n : Nat) where deriving Inhabited, Repr

instance (n : Nat) : BytesDecode (Pad n) where
  decode := do Bytes.skip n; return {}

/-- A type-level literal byte sequence. The decoder verifies the
    upcoming bytes match `bs` exactly; failure surfaces as a parse
    error. Used for structural magic-byte checks (e.g. ELF's
    `\x7fELF`). -/
structure Magic (bs : List UInt8) where deriving Inhabited, Repr

instance (bs : List UInt8) : BytesDecode (Magic bs) where
  decode := do Bytes.expect bs.toArray; return {}

/-- Decode `count` consecutive `α`-entries starting at file offset
    `offset`, using the `BytesDecode α` instance for each. -/
def Bytes.decodeArray (offset count : Nat) [BytesDecode α] : Parser (Array α) := do
  Bytes.seek offset
  let mut entries : Array α := Array.mkEmpty count
  for _ in [:count] do
    entries := entries.push (← BytesDecode.decode)
  return entries

end LeanLoad.Parse

-- ============================================================================
-- Inline sanity: round-trip primitives over hand-crafted inputs.
-- ============================================================================

#guard (LeanLoad.Parse.Parser.run (ByteArray.mk #[0x12]) LeanLoad.Parse.Bytes.u8).toOption == some 0x12
#guard (LeanLoad.Parse.Parser.run (ByteArray.mk #[0x34, 0x12]) LeanLoad.Parse.Bytes.u16le).toOption == some 0x1234
#guard (LeanLoad.Parse.Parser.run (ByteArray.mk #[0x78, 0x56, 0x34, 0x12]) LeanLoad.Parse.Bytes.u32le).toOption == some 0x12345678
